name: group8
channels:
  - defaults
dependencies:
  - altair=5.0.1
  - blas=1.0=openblas (mac) / blas=1.0=mkl (windows)
  - imbalanced-learn 0.12.0 
  - ipykernel 6.28
  - joblib=1.2.0 
  - matplotlib=3.8.0
  - numpy=1.23.5
  - pandas=2.1.4
  - statsmodels=0.14.1
  - pip=23.3.1
  - plotly=5.9.0
  - python=3.11.0
  - python-slugify=5.0.2
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - xgboost=1.7.3

